---
title: "run_MCBE test"
author: "Nikolai Klibansky"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r global_options, echo=FALSE, comment=NA, message=FALSE, warning=FALSE}
library(bamExtras)
library(knitr)

opts_chunk$set(comment=NA,echo=FALSE,message=FALSE,warning=FALSE,fig.height=6,fig.width=6)
```

```{r run null MCBE, eval=FALSE}
# run MCBE which reruns the base model multiple times

run_MCBE("RedPorgy",dir_bam_base="RePo_base", dir_bam_sim="RePo_sim",
         fn_par=list(), 
         data_type_resamp=c() # shut off resampling of data
         )

MCBE_RePo_null <- summarize_MCBE(dir_bam_sim="RePo_sim")
```

```{r profiling}
# profile on custom parameter (not one of the standard defaults)
dir_tmp <- "prof_slope_sel_cHL2"
if(!dir.exists(dir_tmp)){
  dir.create(dir_tmp)
}

abb_i <- "RePo"

run_MCBE("RedPorgy",dir_bam_base=paste0(abb_i,"_base"), dir_bam_sim=paste0(abb_i,"_sim"),
         fn_par=list(set_slope_sel_cHL2 = "seq(1,15,length=nsim)"), # Provide a vector of values to try
         fix_par = "set_slope_sel_cHL2",                            # Fix the parameter
         data_type_resamp=c() # shut off resampling of data
         )

      # Move MCBE files to MCBE directory
  file.copy(
    from=paste0(abb_i,c("_base","_sim","_sim_fail")),
    to=dir_tmp,
    overwrite = TRUE,
    recursive = TRUE)
  unlink(paste0(abb_i,c("_base","_sim","_sim_fail")),recursive = TRUE)

MCBE_RePo_prof <- summarize_MCBE(dir_bam_sim=file.path(dir_tmp,"RePo_sim"))

# plot profile


```

```{r run default MCBE, eval=FALSE}
run_MCBE("AtlanticMenhaden", dir_bam_base="AtMe_base", dir_bam_sim="AtMe_sim")
run_MCBE("BlackSeaBass", dir_bam_base="BlSB_base", dir_bam_sim="BlSB_sim")
run_MCBE("BluelineTilefish", dir_bam_base="BlTi_base", dir_bam_sim="BlTi_sim")
run_MCBE("Cobia", dir_bam_base="Cobi_base", dir_bam_sim="Cobi_sim")
run_MCBE("GagGrouper", dir_bam_base="GaGr_base", dir_bam_sim="GaGr_sim")
run_MCBE("GrayTriggerfish", dir_bam_base="GrTr_base", dir_bam_sim="GrTr_sim")
run_MCBE("GreaterAmberjack", dir_bam_base="GrAm_base", dir_bam_sim="GrAm_sim")
run_MCBE("RedGrouper", dir_bam_base="ReGr_base", dir_bam_sim="ReGr_sim")
run_MCBE("RedPorgy", dir_bam_base="RePo_base", dir_bam_sim="RePo_sim")
run_MCBE("RedSnapper", dir_bam_base="ReSn_base", dir_bam_sim="ReSn_sim")
run_MCBE("ScampGrouper", dir_bam_base="ScGr_base", dir_bam_sim="ScGr_sim")
run_MCBE("SnowyGrouper", dir_bam_base="SnGr_base", dir_bam_sim="SnGr_sim")
run_MCBE("Tilefish", dir_bam_base="Tile_base", dir_bam_sim="Tile_sim")
run_MCBE("VermilionSnapper", dir_bam_base="VeSn_base", dir_bam_sim="VeSn_sim")
```
